sudo: false

language: php

env:
  global:
    - COMPOSER_ROOT_VERSION="4.0.x-dev"

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL
    - php: 7.0
      env: DB=PGSQL
    - php: 7.1
      env: DB=MYSQL

before_script:
 - phpenv rehash

 - composer install --prefer-dist
 - if [[ $DB == PGSQL ]]; then composer require --prefer-dist --no-update silverstripe/postgresql:2.0.x-dev; fi
 - composer update

script:
 - vendor/bin/phpunit tests/
